package gae.piaz.service;

import gae.piaz.domain.Order;
import gae.piaz.domain.dto.OrderDTO;
import org.mapstruct.Mapper;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@Mapper(componentModel = "spring")
public interface OrderMapper {

    Order toEntity(OrderDTO dto);

    OrderDTO toDto(Order entity);
}
