spring:

  datasource:
    username: postgres
    url: jdbc:postgresql://db-service:5432/postgres?currentSchema=library
    platform: postgres
    password: postgres
    hikari:
      maximumPoolSize: ${POOL_SIZE}
      minimum-idle: ${POOL_SIZE}
      poolName: TEST-POOL
      idleTimeout: 1800000

  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: library
    show-sql: 'false'
    hibernate:
      ddl-auto: none

server:
  port: '8080'
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: spring-jdbc
    export:
      influx:
        db: k6
        uri: http://influxdb:8086
        step: 15s
        autoCreateDb: false