spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://db-service:5432/postgres?currentSchema=library #db-service | localhost
    platform: postgres
    password: postgres
    hikari:
      maximumPoolSize: 20

  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: library
    show-sql: 'false'
    hibernate:
      ddl-auto: validate
server:
  port: '8080'
