spring:

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
    platform: postgres
    password: postgres
    hikari:
      maximumPoolSize: 20
      minimum-idle: 20

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics
  metrics:
    export:
      influx:
        uri: http://localhost:8086