spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      initial-size: 20
      max-size: 20

management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086